# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /

spring:
  redis:
    # 地址
    host: 192.168.1.18
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码(如没有密码请注释掉)
    password: 123456
    # 连接超时时间
    timeout: 10s
    # 是否开启ssl
    ssl: false

redisson:
  # redis key前缀
  keyPrefix: xkc
  # 线程池数量
  threads: 4
  # Netty线程池数量
  nettyThreads: 8
  # 单节点配置
  singleServerConfig:
    # 客户端名称
    clientName: ${xkc-iot.name}
    # 最小空闲连接数
    connectionMinimumIdleSize: 8
    # 连接池大小
    connectionPoolSize: 32
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 10000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50

wx:
  mp:
    app-id: '@app-id'
    secret: '@secret'
    token: '@token'
    aesKey: '@aesKey'
    config-storage:
      type: redisson
      key-prefix: wxmp
      redis:
        host: 192.168.1.18
        port: 6379
        password: 123456
        database: 0
        timeout: 10000
      http-client-type: HttpClient
      http-proxy-host: ''
      http-proxy-port: ''
      http-proxy-username: ''
      http-proxy-password: ''
  miniapp:
    appid: '@appid'
    secret: '@secret'
    token: '@token'
    aesKey: '@aesKey'
    config-storage:
      type: redisson
      key-prefix: wxwa
      redis:
        host: 192.168.1.18
        port: 6379
        password: 123456
        database: 0
        timeout: 10000
      http-client-type: HttpClient
      http-proxy-host: ''
      http-proxy-port: ''
      http-proxy-username: ''
      http-proxy-password: ''
    # 消息格式，XML或者JSON.
    msgDataFormat: 'XML'
